export default {
  state: {
    descriptionData: [
      { name: "Arroz", value: "36" },
      { name: "Feijão", value: "47" },
      { name: "Carne", value: "150" },
      { name: "Leite", value: "80" },
      { name: "Farinha", value: "34" },
      { name: "Macarrão", value: "59" },
      { name: "Òleo", value: "45" },
      { name: "Azeite", value: "15" },
      { name: "Sal", value: "10" },
      { name: "Gelatina", value: "300" },
      { name: "Frango", value: "150" },
    ],
    months: [
      "Janeiro",
      "Fevereiro",
      "Março",
      "Abril",
      "Maio",
      "Junho",
      "Julho",
      "Agosto",
      "Setembro",
      "Outubro",
      "Novembro",
      "Dezembro",
    ],
  },
};
