export default {
  state: {
    header: [
      "Box",
      "Nº",
      "Aluno",
      "Sobrenome",
      "Matemática",
      "Português",
      "Ciência",
      "Geografia",
      "História",
      "Fisica",
      "Filozofia",
      "Inglês",
    ],
    params: [
      {
        number: 12354,
        name: "Jefferson",
        lastName: "Rocha",
        matematica: 7.5,
        portugues: 6.4,
        ciencia: 8.9,
        geografia: 9.0,
        historia: 4.5,
        fisica: 8.0,
        filozofia: 1.5,
        ingles: 7.5,
      },
      {
        number: 12354,
        name: "Matheus",
        lastName: "Silva",
        matematica: 7.5,
        portugues: 1.4,
        ciencia: 8.9,
        geografia: 9.0,
        historia: 6.5,
        fisica: 8.0,
        filozofia: 4.5,
        ingles: 7.5,
      },
      {
        number: 12354,
        name: "Joana",
        lastName: "Gonsalves",
        matematica: 1.5,
        portugues: 6.4,
        ciencia: 8.9,
        geografia: 9.0,
        historia: 8.5,
        fisica: 8.0,
        filozofia: 1.5,
        ingles: 2.5,
      },
      {
        number: 12354,
        name: "Gustavo",
        lastName: "Lima",
        matematica: 7.5,
        portugues: 2.4,
        ciencia: 8.9,
        geografia: 9.0,
        historia: 8.5,
        fisica: 4.0,
        filozofia: 1.5,
        ingles: 7.5,
      },
      {
        number: 12354,
        name: "Rozana",
        lastName: "Macedo",
        matematica: 4.5,
        portugues: 6.4,
        ciencia: 2.9,
        geografia: 9.0,
        historia: 4.5,
        fisica: 5.0,
        filozofia: 1.5,
        ingles: 7.5,
      },
    ],
  },
};
